import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <nav style={{ display: "flex", gap: 16, padding: "12px 16px", borderBottom: "1px solid #eee" }}>
          <a href="/">Chat</a>
          <a href="/admin">Admin</a>
          <a href="/settings">Settings</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
